apiVersion: v1
kind: SopsSecret
metadata:
    name: sops-harbor-config
    namespace: sops-harbor
type: Opaque
stringData:
    CONFIG_OVERWRITE_JSON: ENC[AES256_GCM,data:5X1zsqrFBQwG7cnX2JwXTutfZbE0176h+yL/oFCV97w2HQLjpI7AM56EtawlxFBWCNgVJnuSQhf2v/L9gWSJ/dbgRjSzQz2uRmBzeI4l2VePlDbBQ7f2esau8rwZ2KGLrwigQtQyql4ZiJBptAf753f7jY7lec2jmW7PF5v3+zq7JKr1Ql8+hTswDfkNIiLjCKwdOKJHegEg6RIg7zQkJLXRdLm5VYHsIG9cZYFzHZbdu2r/yxuE+4BLzMHwzF9Pv9/fce/pd4QKocMkhOEe/tlfE/nOGwdx+HI/ycrun2cO9c15XXpjLpaUBJFvgaD4pSSV8WcrMbNUrDOe8TRgFzJ7FBVib2zr/SeTyB9ZE8KEmRGlrAtScgQlCJJ1jIYqThGHqMdsMPXYiTPysnzuw7kO5LuQsx4doBMR3EqpF7apT440t4TvjmoFc+iJlRb5PHWqjPltn06IGByKuLxTkQCqYUhzGlSwiYlFYYMnf+5bx4gQcEyglVh3JI7FQtZ43tkVAMxMo02hqp99gUNBJMY=,iv:Cmb9TycXOOrXHlzw4BZ5lRq7pHfhUXd61puH7U35v04=,tag:h/qRBRUR7lTaayAeHlSvEA==,type:str]
sops:
    age:
        - recipient: age1rqgkdz06pmtrwax6ttykfc3macheykuk4vnpyrxxhw8qdgssk3jqma2tvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSmRRbVV0YUJyU044R3lG
            K3NmbEc4N0hFY2hCaEpPeXJMekgxaDIwN1drCjhzT2MwQ01PNDJlNy83clA0bW8w
            SlZ4dWh4dmFFcFg1QVBJdXhGOFI5RWMKLS0tIGdtdGw0L3dlc3pRUnczMFprdzYw
            WjhaWmJGTlYwLzRtbE5ObXFUUCtMQnMKqNGOx9qgKXEgQ2azMXaztXsH7ld4A5Fb
            OVMdnvkRJ+vM56gIz2U86E+gT1EEUO4cfufOEPVn4mrL3Yg2U9r+yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T14:30:43Z"
    mac: ENC[AES256_GCM,data:EPxUWWe6F93NO34d/QARQpEsCIQMCvJnHF1Pvyp5ECHe8uP2QTNJ2H9ImzRmlypHYSBHdsByPTB1awHBoHcwAMnC1ytz2ubqIaE8lC5vMgvJnp7PF3oyadKFiLx3ZiitYIoLszSq+0LGPuXMT86voG/uPGM5BhT65hDA1YODkWg=,iv:CNj6lP2T0ZsVQYndy+ncuy3QqkqEdi2rCCS0P1c9w4g=,tag:kskNLNJJ0nFRcwOWLXitIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
