apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - files:
      - admin.hcl
      - infralytics-admin.hcl
      - infralytics-reader.hcl
    name: vault-policies
    options:
      disableNameSuffixHash: true
kind: Kustomization
resources:
  - vault-cert.yaml
  - vault-ingress.yaml
  - vault-setup-wf.yaml
  - vault-unseal-wf.yaml
  - workflow-rbac.yaml
secretGenerator:
  - literals:
      - oidc-issuer=https://sops-auth.orlandotorres.dev/realms/dev-test
      - oidc-client=vault-prod
      - oidc-secret=l2FLwizbuasxP2OaxXqPeBwCkyOZ4ux2
    name: oidc-secret